$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline

display_name: azureml-genomics-pipeline
experiment_name: genomics-pipeline-cli
description: Genomics pipeline with parallel jobs

settings:
  default_compute: azureml:genomics-cluster

jobs:
  seq_quality_control:
    type: parallel
    component: azureml:seq_quality_control@latest
    inputs:
      input_folder: 
        type: uri_folder
        path: azureml:genomic_data@latest
        mode: ro_mount
    outputs:
      output_folder:
        type: uri_folder
        name: seq_quality_output
        version: 1
        mode: rw_mount
      output_files:
        type: uri_file
        mode: rw_mount

  bwa_indexer:
    type: command
    component: azureml:component_bwa_indexer@latest
    inputs:
      ref_genome:
        type: uri_file
        path: azureml:hg38@latest
        mode: download
    outputs:
      ref_index_folder:
        type: uri_folder
        path: azureml://datastores/workspaceblobstore/paths/bwa_index_output/
        mode: rw_mount

  bwa:
    type: parallel
    component: azureml:bwa@latest
    inputs:
      input_folder: 
        type: uri_folder
        path: azureml:genomic_data@latest
        mode: ro_mount
      index_folder:
        type: uri_folder
        path: ${{parent.jobs.bwa_indexer.outputs.ref_index_folder}}
        mode: ro_mount
    outputs:
      bwa_output_folder:
        type: uri_folder
        name: bwa_output
        mode: rw_mount
      output_files:
        type: uri_file
        mode: rw_mount